project:
  type: website
  output-dir: docs #this will determine where your rendered pages (in this example, Project1 and 2) are stored. 
  
website:
  title: "DACSS-604_Fall24:Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
     # - icon: twitter
     #    href: https://twitter.com/
      - icon: github
        href: https://github.com/dongericoyu/webpage-demo
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Erico Yu"

format:
  html:
    theme: cerulean
    toc: true

editor: source

#remember to inlude the following lines to include all files in the `files/` folder that you want to link to.
resources: 
  - "files/**"
